- CONTRIBUTING-ko_kr.md
- CONTRIBUTING.md
- package.json
- packages/core/package.json
1. add `sideEffects`'s `**/*.css.ts`
2. update `engines` node: `"18.x"` -> `">=20.x"`
During the build process, the following warning was repeatedly displayed:
```shell
▲ [WARNING] Ignoring this import because "src/styles/global.css.ts" was marked as having no side effects [ignored-bare-import]
src/styles/contract.css.ts:3:11:
3 │     import './global.css';
```
**Cause**: `vanilla-extract` injects styles simply by importing `.css.ts` files. However, the `**/*.css.ts` pattern was missing from the `sideEffects` field in `@vapor-ui/core`'s `package.json`. This caused the build tool (`tsup`) to treat these imports as unnecessary code and remove them via tree-shaking.
**Impact**: This created a critical potential bug where essential CSS, such as global styles, could be omitted from the final …
> fix(build): Resolve build warnings and update Node.js version requirement

- apps/website/src/constants/site-links.tsx
This pull request refactors the `navLinks` icons in `apps/website/src/constants/site-links.tsx` to use pre-built components from the `@vapor-ui/icons` package instead of custom `Image` components. This change simplifies the code and improves maintainability.
Refactoring for icon components:
* Replaced custom `Image` components with pre-built icon components (`FigmaColorIcon`, `DiscordColorIcon`, `GithubIcon`) from `@vapor-ui/icons`. This eliminates the need for manual styling and ensures consistent icon rendering.
> refactor: replace image components with icon components for navigation links

- .changeset/quiet-berries-act.md
- packages/core/tsup.config.ts
Temporarily disable `tsup` splitting due to CSS fetching issues.
> chore: tsup spliting update

- .changeset/brave-forks-appear.md
- apps/website/content/docs/getting-started/installation.mdx
- apps/website/content/docs/getting-started/theming.mdx
- packages/core/src/components/card/card.css.ts
- packages/core/src/components/create-theme-config/create-theme-config.tsx
- packages/core/src/components/create-theme-config/index.ts
- packages/core/src/components/theme-provider/theme-injector.ts
- packages/core/src/components/theme-provider/theme-provider.tsx
- packages/core/src/index.ts
- packages/core/src/styles/global.css.ts
<details>
<summary>Korean</summary>
* RSC (React Server Components) 환경에서 `createThemeConfig`가 지원되지 않던 문제를 해결했습니다.
* Theming 관련 문서 내용을 최신 변경사항에 맞게 올바르게 수정했습니다.
</details>
<br/>
- Fixed an issue where createThemeConfig was not supported in the RSC (React Server Components) environment.
- Updated the theming documentation to reflect the recent changes accurately.
> fix(createThemeConfig): Support RSC

- packages/core/package.json
- packages/core/tsup.config.ts
- .d.ts 파일을 dist/types 하위가 아니라, dist 및 dist/components 하위에 생성
- flex, box처럼 .css.ts 파일이 없는 컴포넌트에서는 index.css 임포트 구문 제거
> build: remove dist/types directory

- packages/core/src/components/box/box.stories.tsx
- packages/core/src/components/box/box.tsx
- packages/core/src/components/button/button.stories.tsx
- packages/core/src/components/flex/flex.stories.tsx
- packages/core/src/components/flex/flex.tsx
- packages/core/src/components/grid/grid.stories.tsx
- packages/core/src/components/grid/grid.tsx
- packages/core/src/components/h-stack/h-stack.stories.tsx
- packages/core/src/components/h-stack/h-stack.tsx
- packages/core/src/components/switch/switch.stories.tsx
- packages/core/src/components/text-input/text-input.stories.tsx
- packages/core/src/components/text/text.stories.tsx
- packages/core/src/components/v-stack/v-stack.stories.tsx
- packages/core/src/components/v-stack/v-stack.tsx
- packages/core/src/styles/sprinkles.css.ts
- layout props 복구
- Box에만 기본적으로 추가해두었음
- 그리고 Grid, Flex, VStack, HStack는 Box를 사용하고 있기 때문에 마찬가지로 추가되어 있음
- 타입 추론이 불가능했던 이유는, backgroundColor, foregroundColor를 동적으로 생성하고 있기 때문이었음
- 그래서 정적으로 일일이 생성해주었음
- foregroundColor는 일단 제거해두었음. color라는 이름 대신 foregroundColor로 추가하고 싶었는데, 아직까지는 방법을 찾지 못했음
> feat: add layout recipes

- apps/website/content/docs/getting-started/installation.mdx
- apps/website/content/docs/getting-started/theming.mdx
- apps/website/content/docs/theming/next-app.mdx
- apps/website/content/docs/theming/vite.mdx
- packages/core/README.md
This pull request updates installation instructions across multiple documentation files to explicitly recommend installing the latest versions of Vapor UI packages. It also includes minor improvements to code organization in the Next.js theming guide for better readability.
The following files now use `@latest` in their `npm install` commands to ensure consistency and clarity when installing Vapor UI packages:
- `apps/website/content/docs/getting-started/installation.mdx`
- `apps/website/content/docs/getting-started/theming.mdx`  
- `apps/website/content/docs/theming/next-app.mdx`
- `apps/website/content/docs/theming/vite.mdx`
- `packages/core/README.md`
- Reordered `import type { Metadata } from 'next'` for clearer logical grouping of imports in `next-app.mdx`.
- Removed a duplicate …
> docs : Update installation instructions to use the latest version of @vapor-ui

- .changeset/warm-pens-find.md
- packages/core/package.json
- packages/core/src/styles/tailwind-preset.css.ts
- packages/core/tsup.config.ts
<details>
<summary><strong>한국어</strong></summary>
@vapor-ui/core가 Tailwind CSS v4를 공식적으로 지원하도록 기능을 추가합니다.
이번 변경을 통해, 개발자는 @vapor-ui/core의 모든 디자인 토큰을 `v-` 접두사가 붙은 Tailwind 유틸리티 클래스로 직접 사용할 수 있습니다.
Tailwind CSS v4부터는 `tailwind.config.js` 파일을 통한 설정보다, CSS의 `@theme`과 `@layer`를 사용하는 CSS-first 방식을 공식적으로 권장하고 있습니다.
이에 따라, 별도의 JS 설정을 요구하는 대신 사용자가 CSS 파일을 임포트하는 것만으로 모든 기능이 동작하도록 구현했습니다. `dist/tailwind.css` 파일 내에 `@theme`과 `@utility` 규칙을 사용하여 모든 토큰 매핑과 유틸리티 클래스 생성을 처리합니다.
이 과정에서 [Tailwind 공식 문서에 정의된 테마 변수 네임스페이스](https://tailwindcss.com/docs/theme#theme-variable-namespaces)(`--color-*`, `--spacing-*` 등)를 준수했습니다. 이 규칙을 지켜야만 Tailwind 엔진이 변수를 올바르게 인식하고 `bg-*`, `p-*` 와 같은 유틸리티 클래스를 자동으로 생성할 수 있기 때문입니다.
의도치 않은 유틸리티 클래스가 생성되는 사이드 이펙트를 막기 위해 `@theme`과 `@utility`의 역할을 분리했습니다.
예를 들어, 시맨틱 토큰인 …
> feat: Add Tailwind CSS v4 Support

- .changeset/giant-walls-switch.md
- packages/core/src/styles/index.ts
- packages/core/tsup.config.ts
The existing build script used a method of dynamically injecting `import "./index.css"` statements into each component's JavaScript file. While this approach theoretically enabled **CSS tree-shaking**, it caused serious usability issues:
- CSS `@layer` priority issues: As components were dynamically imported, CSS injection order wasn't guaranteed, causing our designed `@layer` hierarchy (e.g., `reset`, `theme`, `component`) to break.
- High configuration barrier and learning curve: To resolve this issue, users were forced to implement complex additional configurations:
1. Setting up separate PostCSS plugins like `postcss-import` or Vite plugins
2. Manually declaring `@layer` order at the top of files like `globals.css`
3. Ensuring `globals.css` is imported before any other components at …
> refactor(build): Improve DX by Overhauling CSS Bundling Strategy

- README.md
This pull request updates the links in the `README.md` file to reflect changes in the documentation structure for Vapor UI. The updates ensure that users are directed to the correct sections of the official documentation.
* Updated the "Usage" link to point to the new "Getting Started" section in the official documentation (`https://vapor-ui.goorm.io/docs/getting-started/installation`) for both the overview and detailed usage instructions. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L22-R22) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L34-R34)
> docs(readme): fix document site link

- .prettierrc.js
- apps/website/src/app/layout.tsx
This pull request introduces changes to the import order configuration in `.prettierrc.js` and adjusts the import of `./global.css` in `layout.tsx` to align with the updated order. These changes aim to ensure consistent styling and adherence to the configured import order.
* [`.prettierrc.js`](diffhunk://#diff-7312296367dd7c725b9beb500d7dab7bbeeb2aa03a1010a3fb2935f826d03fa6L9-R9): Updated the `importOrder` to prioritize `./global.css` at the top of imports, ensuring consistent placement of global styles.
* [`apps/website/src/app/layout.tsx`](diffhunk://#diff-d9c8dd9cba006bd0472a885a8f8f9ab9483b9fc5bb065a8cd4f6375e5db1a8cdR3): Moved the import of `./global.css` to the top of the file to comply with the new import order configuration.
> docs: update import order and include global CSS in layout

- .changeset/brown-hats-shave.md
- packages/core/src/components/radio-group/radio-group.tsx
- During this [PR](https://github.com/goorm-dev/vapor-ui/pull/125), a functional bug was discovered and fixed:
- variant props (e.g., visuallyHidden) were being incorrectly injected as HTML tag attributes, leading to error logs in the browser console.
- This was resolved by separating variantProps and sharedProps
> fix(radio-group): remove incorrectly injected props

- .changeset/fine-buttons-pull.md
- packages/core/src/styles/index.ts
#141 
This PR fixes a bug where the `foreground` utility was not being applied because its mixin was missing from the main style entry point.
- **Problem:** The CSS for the `foreground` utility was not included in the final stylesheet build.
- **Solution:** Added the `foreground` mixin to the style entry point, ensuring it is correctly compiled and bundled.
**Out of Scope:**
This change is a hotfix focused solely on resolving the `foreground` issue. It does not include a broader refactoring of the style import structure.
Before submitting the PR, please make sure you have checked all of the following items.
> fix(style): Add foreground mixin to style entry point

- .changeset/brown-hats-shave.md
- packages/core/src/components/radio-group/radio-group.test.tsx
- packages/core/src/components/radio-group/radio-group.tsx
- Wrote Unit tests for the RadioGroup component.
- Test is currently failing.
- This issue requires a modification to the component's implementation, which has been addressed in a separate pull request. ([here](https://github.com/goorm-dev/vapor-ui/pull/126))
> feat: add radio-group unit test

- packages/core/src/components/radio-group/radio-group.test.tsx
- packages/core/vitest.config.ts
- X
1. When the `focus()` method is called, it internally updates React's state. React Testing Library (RTL) requires that any action causing a state update must be wrapped in the act() function. This was not being done, which was causing a warning message.
2. Added @vapor-ui/icons to the ssr.noExternal field.
- Packages provided to ssr.noExternal are included in the bundle at build time.
- Previously, @vapor-ui/icons was not included in the build bundle, resulting in an error.
- Therefore, the configuration has been updated to include @vapor-ui/icons in the test environment.
Before submitting the PR, please make sure you have checked all of the following items.
> fix: resolve errors about unit test

- packages/core/src/components/checkbox/checkbox.stories.tsx
Clicking the Checkbox does not change its state. 
This is because Storybook's `{...args}` prop is overriding all state properties.
https://github.com/user-attachments/assets/76a90c2f-af77-42d0-afd0-316a8c3ab8db
So, relocated `{...args}`
> fix: resolved fixed checkbox state

- packages/core/src/components/dialog/dialog.css.ts
- Add default z-index in dialog and TODO comment for any other zIndex things.
- Add maxHeight for Scroll type in Design system.
Before submitting the PR, please make sure you have checked all of the following items.
> fix: Add z-index values in dialog and add sync with overflow.

- .prettierrc.js
- apps/website/src/app/playground/_components/radio-button-group/radio-button-group.tsx
- apps/website/src/app/playground/_components/theme-panel/theme-panel.tsx
- apps/website/src/app/playground/layout.tsx
- packages/core/src/styles/index.ts
Currently, all Prettier CI tests are failing due to an import sort error in `styles/index.ts` within the core package. While this can be resolved by improving the tsup build configuration, this task has been delayed by other priorities.
As an immediate fix for the Prettier error, I have set the `importOrderSideEffects: false` option to ignore formatting for side-effect imports.
Since this modification is a temporary workaround, it would be beneficial to consider a more sustainable long-term solution. Briefly, I believe adopting next-generation linting tools like oxlint and biome could be a promising approach. For a comparison of these two tools, please refer to this [discussion](https://github.com/biomejs/biome/discussions/1281).
Here is a brief summary:
**Biome**
- `+` Aims to provide …
> chore: ignore formatting side-effect import

- .changeset/fluffy-sites-slide.md
- packages/core/src/components/checkbox/checkbox.css.ts
Fixes #206
- Change hover interaction pesudo class not to use borderRadius and set parent element `overflow: hidden`
Before submitting the PR, please make sure you have checked all of the following items.
> fix: Fix checkbox borderRadius sync error

- .changeset/new-games-mix.md
- packages/core/tsup.config.ts
N/A
- CSS build included automatic Pretendard font loading via tsup banner configuration
- Font was automatically imported in generated CSS files: `@import url("https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css");`
- Removed `banner.css` option from tsup config in `packages/core/tsup.config.ts:138-141`
- Font loading is now the responsibility of the consuming application
- Applications must manually include Pretendard or their preferred font
1. **Flexibility**: Applications can choose their preferred font loading strategy (CDN, self-hosted, variable fonts, etc.)
2. **Performance**: Avoids duplicate font loading when applications already have font management
3. **Industry Standard**: Aligns with how other major design …
> feat: Remove Font Loading from CSS Build
